# TODO: Add build and deploy stage (should only run on main branch)
stages:
  - lint
  - test

lint with black:
  stage: lint
  tags:
    - test-runner
  image: python:3.10-slim-buster
  script:
    - python --version # For debugging
    - pip install black
    - black .
    - black --check .

test:
  tags:
    - test-runner
  stage: test
  image: python:3.10-slim-buster
  script:
    - echo "Define test script here"
    - pip install -r requirements.txt
    - pytest tests
